/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 20-lis-2022 17:02:58 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Gotowka` CASCADE
;

DROP TABLE IF EXISTS `Kartakredytowa` CASCADE
;

DROP TABLE IF EXISTS `Klient` CASCADE
;

DROP TABLE IF EXISTS `Kredyt` CASCADE
;

DROP TABLE IF EXISTS `Platnosc` CASCADE
;

DROP TABLE IF EXISTS `Pracownik` CASCADE
;

DROP TABLE IF EXISTS `Przelew` CASCADE
;

DROP TABLE IF EXISTS `Rejestrkredytowy` CASCADE
;

DROP TABLE IF EXISTS `Sesja` CASCADE
;

DROP TABLE IF EXISTS `Transakcja` CASCADE
;

DROP TABLE IF EXISTS `Użytkownik` CASCADE
;

DROP TABLE IF EXISTS `Wniosekokredyt` CASCADE
;

/* Create Tables */

CREATE TABLE `Gotowka`
(
	`Iloscbanknotow` INT NULL,
	`Miejsceplatnosci` String NULL,
	`Nadawca` String NULL,
	`GotowkaID` INT NOT NULL,
	CONSTRAINT `PK_Gotowka` PRIMARY KEY (`GotowkaID` ASC)
)

;

CREATE TABLE `Kartakredytowa`
(
	`Cvc` INT NULL,
	`Datawaznosci` DATETIME NULL,
	`Nrkarty` INT NULL,
	`Wlasciciel` String NULL,
	`KartakredytowaID` INT NOT NULL,
	CONSTRAINT `PK_Kartakredytowa` PRIMARY KEY (`KartakredytowaID` ASC)
)

;

CREATE TABLE `Klient`
(
	`Adreszamieszkania` String NULL,
	`Dataurodzenia` DATETIME NULL,
	`Nrpesel` INT NULL,
	`KlientID` INT NOT NULL,
	CONSTRAINT `PK_Klient` PRIMARY KEY (`KlientID` ASC)
)

;

CREATE TABLE `Kredyt`
(
	`Datasplacenia` DATETIME NULL,
	`Datazawarciaumowy` DATETIME NULL,
	`Iloscrat` INT NULL,
	`Ilosczaleglychrat` INT NULL,
	`Kwota` INT NULL,
	`Kwotapozostaladosplaty` INT NULL,
	`Status` INT NULL,
	`KredytID` INT NOT NULL,
	`KlientID` INT NULL,
	`RejestrkredytowyID` INT NULL,
	CONSTRAINT `PK_Kredyt` PRIMARY KEY (`KredytID` ASC)
)

;

CREATE TABLE `Platnosc`
(
	`Data` DATETIME NULL,
	`Kwota` INT NULL,
	`PlatnoscID` INT NOT NULL,
	`TransakcjaID` INT NULL,
	CONSTRAINT `PK_Platnosc` PRIMARY KEY (`PlatnoscID` ASC)
)

;

CREATE TABLE `Pracownik`
(
	`Stanowisko` String NULL,
	`Uprawnienia` INT NULL,
	`PracownikID` INT NOT NULL,
	`RejestrkredytowyID` INT NULL,
	CONSTRAINT `PK_Pracownik` PRIMARY KEY (`PracownikID` ASC)
)

;

CREATE TABLE `Przelew`
(
	`Nadawca` String NULL,
	`Nrkonta` INT NULL,
	`PrzelewID` INT NOT NULL,
	CONSTRAINT `PK_Przelew` PRIMARY KEY (`PrzelewID` ASC)
)

;

CREATE TABLE `Rejestrkredytowy`
(
	`Datautworzenia` DATETIME NULL,
	`Oddzialbanku` String NULL,
	`RejestrkredytowyID` INT NOT NULL,
	CONSTRAINT `PK_Rejestrkredytowy` PRIMARY KEY (`RejestrkredytowyID` ASC)
)

;

CREATE TABLE `Sesja`
(
	`Adresip` INT NULL,
	`Datarozpoczecia` INT NULL,
	`Datazakonczenia` INT NULL,
	`Token` INT NULL,
	`SesjaID` INT NOT NULL,
	`UżytkownikID` INT NULL,
	CONSTRAINT `PK_Sesja` PRIMARY KEY (`SesjaID` ASC)
)

;

CREATE TABLE `Transakcja`
(
	`Datarozpoczecia` DATETIME NULL,
	`Datazakonczenia` DATETIME NULL,
	`Status` INT NULL,
	`TransakcjaID` INT NOT NULL,
	`KlientID` INT NULL,
	`KredytID` INT NULL,
	CONSTRAINT `PK_Transakcja` PRIMARY KEY (`TransakcjaID` ASC)
)

;

CREATE TABLE `Użytkownik`
(
	`Email` String NULL,
	`Haslo` String NULL,
	`Imie` String NULL,
	`Nazwisko` String NULL,
	`Nrtel` String NULL,
	`UżytkownikID` INT NOT NULL,
	CONSTRAINT `PK_Użytkownik` PRIMARY KEY (`UżytkownikID` ASC)
)

;

CREATE TABLE `Wniosekokredyt`
(
	`Datazlozenia` DATETIME NULL,
	`Iloscrat` INT NULL,
	`Kwota` INT NULL,
	`Oprocentowanie` INT NULL,
	`Status` INT NULL,
	`WniosekokredytID` INT NOT NULL,
	`KlientID` INT NULL,
	`RejestrkredytowyID` INT NULL,
	CONSTRAINT `PK_Wniosekokredyt` PRIMARY KEY (`WniosekokredytID` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Gotowka` 
 ADD CONSTRAINT `FK_Gotowka_Platnosc`
	FOREIGN KEY (`GotowkaID`) REFERENCES `Platnosc` (`PlatnoscID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Kartakredytowa` 
 ADD CONSTRAINT `FK_KartaKredytowa_Platnosc`
	FOREIGN KEY (`KartakredytowaID`) REFERENCES `Platnosc` (`PlatnoscID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Klient` 
 ADD CONSTRAINT `FK_Klient_Użytkownik`
	FOREIGN KEY (`KlientID`) REFERENCES `Użytkownik` (`UżytkownikID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Kredyt` 
 ADD CONSTRAINT `FK_Kredyt_Klient`
	FOREIGN KEY (`KlientID`) REFERENCES `Klient` (`KlientID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Kredyt` 
 ADD CONSTRAINT `FK_Kredyt_Rejestrkredytowy`
	FOREIGN KEY (`RejestrkredytowyID`) REFERENCES `Rejestrkredytowy` (`RejestrkredytowyID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Platnosc` 
 ADD CONSTRAINT `FK_Platnosc_Transakcja`
	FOREIGN KEY (`TransakcjaID`) REFERENCES `Transakcja` (`TransakcjaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Pracownik` 
 ADD CONSTRAINT `FK_Pracownik_Użytkownik`
	FOREIGN KEY (`PracownikID`) REFERENCES `Użytkownik` (`UżytkownikID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Pracownik` 
 ADD CONSTRAINT `FK_Pracownik_Rejestrkredytowy`
	FOREIGN KEY (`RejestrkredytowyID`) REFERENCES `Rejestrkredytowy` (`RejestrkredytowyID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Przelew` 
 ADD CONSTRAINT `FK_Przelew_Platnosc`
	FOREIGN KEY (`PrzelewID`) REFERENCES `Platnosc` (`PlatnoscID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Sesja` 
 ADD CONSTRAINT `FK_Sesja_Użytkownik`
	FOREIGN KEY (`UżytkownikID`) REFERENCES `Użytkownik` (`UżytkownikID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Transakcja` 
 ADD CONSTRAINT `FK_Transakcja_Klient`
	FOREIGN KEY (`KlientID`) REFERENCES `Klient` (`KlientID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Transakcja` 
 ADD CONSTRAINT `FK_Transakcja_Kredyt`
	FOREIGN KEY (`KredytID`) REFERENCES `Kredyt` (`KredytID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Wniosekokredyt` 
 ADD CONSTRAINT `FK_Wniosekokredyt_Klient`
	FOREIGN KEY (`KlientID`) REFERENCES `Klient` (`KlientID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Wniosekokredyt` 
 ADD CONSTRAINT `FK_Wniosekokredyt_Rejestrkredytowy`
	FOREIGN KEY (`RejestrkredytowyID`) REFERENCES `Rejestrkredytowy` (`RejestrkredytowyID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 
